#spring:
#  profiles:
#    active: dev

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pokedex
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Para desenvolvimento