-- Script SQL para importar dados de habilidades
INSERT INTO ability (id, name) VALUES
    (1, 'Overgrow'),
    (2, 'Blaze'),
    (3, 'Torrent'),
    (4, 'Shield Dust'),
    (5, 'Compound Eyes'),
    (6, 'Skilled'),
    (7, 'Shed Skin'),
    (8, 'Run Away'),
    (9, 'Keen Eye'),
    (10, 'Inner Focus'),
    (11, 'Synchronize'),
    (12, 'Clear Body'),
    (13, 'Natural Cure'),
    (14, 'Illuminate'),
    (15, 'Trace'),
    (16, 'Serene Grace'),
    (17, 'Swift Swim'),
    (18, 'Chlorophyll'),
    (19, 'Solar Power'),
    (20, 'Harvest'),
    (21, 'Pickpocket'),
    (22, 'Technician'),
    (23, 'Iron Fist'),
    (24, 'Reckless'),
    (25, 'Defiant'),
    (26, 'Victory Star'),
    (27, 'Mold Breaker'),
    (28, 'Wonder Guard'),
    (29, 'Levitate'),
    (30, 'Immunity'),
    (31, 'Adaptability'),
    (32, 'Analytic'),
    (33, 'Download'),
    (34, 'Forewarn'),
    (35, 'Unburden'),
    (36, 'Infiltrator'),
    (37, 'Cursed Body'),
    (38, 'Fluffy'),
    (39, 'Sap Sipper'),
    (40, 'Storm Drain'),
    (41, 'Water Absorb'),
    (42, 'Dry Skin'),
    (43, 'Thick Fat'),
    (44, 'Ice Body'),
    (45, 'Snow Cloak'),
    (46, 'Sand Veil'),
    (47, 'Flash Fire'),
    (48, 'Flame Body'),
    (49, 'Heatproof'),
    (50, 'Magnet Pull'),
    (51, 'Steelworker'),
    (52, 'Heavy Metal'),
    (53, 'Light Metal'),
    (54, 'Pickup'),
    (55, 'Hustle'),
    (56, 'Cute Charm'),
    (57, 'Marvel Scale'),
    (58, 'Liquid Ooze'),
    (59, 'Poison Heal'),
    (60, 'Regenerator'),
    (61, 'Stench'),
    (62, 'Sweet Veil'),
    (63, 'Flower Gift'),
    (64, 'Leaf Guard'),
    (65, 'Rain Dish'),
    (66, 'Sand Rush'),
    (67, 'Snow Warning'),
    (68, 'Sunny Day'),
    (69, 'Rain Dance'),
    (70, 'Hail'),
    (71, 'Sandstorm'),
    (72, 'Drought'),
    (73, 'Drizzle'),
    (74, 'Swift Swim'),
    (75, 'Chlorophyll'),
    (76, 'Solar Power'),
    (77, 'Harvest'),
    (78, 'Pickpocket'),
    (79, 'Technician'),
    (80, 'Iron Fist'),
    (81, 'Reckless'),
    (82, 'Defiant'),
    (83, 'Victory Star'),
    (84, 'Mold Breaker'),
    (85, 'Wonder Guard'),
    (86, 'Levitate'),
    (87, 'Immunity'),
    (88, 'Adaptability'),
    (89, 'Analytic'),
    (90, 'Download'),
    (91, 'Forewarn'),
    (92, 'Unburden'),
    (93, 'Infiltrator'),
    (94, 'Cursed Body'),
    (95, 'Fluffy'),
    (96, 'Sap Sipper'),
    (97, 'Storm Drain'),
    (98, 'Water Absorb'),
    (99, 'Dry Skin'),
    (100, 'Thick Fat'),
    (101, 'Ice Body'),
    (102, 'Snow Cloak'),
    (103, 'Sand Veil'),
    (104, 'Flash Fire'),
    (105, 'Flame Body'),
    (106, 'Heatproof'),
    (107, 'Magnet Pull'),
    (108, 'Steelworker'),
    (109, 'Heavy Metal'),
    (110, 'Light Metal'),
    (111, 'Pickup'),
    (112, 'Hustle'),
    (113, 'Cute Charm'),
    (114, 'Marvel Scale'),
    (115, 'Liquid Ooze'),
    (116, 'Poison Heal'),
    (117, 'Regenerator'),
    (118, 'Stench'),
    (119, 'Sweet Veil'),
    (120, 'Flower Gift'),
    (121, 'Leaf Guard'),
    (122, 'Rain Dish'),
    (123, 'Sand Rush'),
    (124, 'Snow Warning'),
    (125, 'Sunny Day'),
    (126, 'Rain Dance'),
    (127, 'Hail'),
    (128, 'Sandstorm'),
    (129, 'Drought'),
    (130, 'Drizzle');
