name: SonarQube
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - 'feature/**'
      - 'feat/**'
      - 'fix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'bugfix/**'
      - 'support/**'
      - 'chore/**'
      - 'docs/**'
      - 'style/**'
      - 'refactor/**'
      - 'perf/**'
      - 'test/**'
      - 'ci/**'           
      - 'build/**'       
      - 'revert/**'       
      - 'temp/**'

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info